# Generated by Django 2.0.2 on 2018-02-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('region', models.CharField(choices=[('SAM', 'South America'), ('CAM', 'Central America'), ('EAPAC', 'East Asia / Pacific'), ('NAFR', 'North Africa'), ('WAFR', 'West Africa'), ('CAFR', 'Central Africa'), ('EAFR', 'East Africa')], max_length=20)),
                ('country', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=200)),
                ('incident_date', models.DateField()),
                ('additional_incident_data_infor', models.CharField(max_length=200)),
                ('source_date', models.DateField()),
                ('report_url', models.URLField(max_length=300)),
                ('source', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('LOSS', 'Loss'), ('LOOT', 'Looting'), ('UNTRU', 'Unauthorized transfer or use'), ('CSR', 'Corrupt sale or rent'), ('SEIZ', 'Seizure'), ('DIV', 'Use of diverted weapons(in criminal, terrorist or insurgency incidents)'), ('LAW', 'Law enforcement(law enforcement action, court cases, investigation, government campaigns & action)'), ('DESERT', 'Desertion with weapons'), ('UNPLANNED', 'Unplanned explosions at munitions sites(UEMS)'), ('SAFSEC', 'Safety and security'), ('DISARM', 'Disarmament'), ('AM', 'Weapons amnesty'), ('OTHER', 'Other')], max_length=20)),
                ('report_code', models.CharField(max_length=20)),
                ('weapons', models.CharField(choices=[('PISTOL', 'Pistol'), ('REVOLVER', 'Revolver'), ('RIFEL', 'Rifel'), ('SHOTGUN', 'Shotgun'), ('SMALL_ARMS_AMMUNITION', 'Small Arms Ammunition'), ('MACHINE_GUN', 'Machine Gun'), ('EXPLOSIVE_ORDNANCE', 'Explosive Ordnance'), ('ATGM', 'ATGM'), ('MANPADS', 'MANPADS'), ('UNSPECIFIED', 'Unspecified'), ('OTHER', 'Other')], max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Report')),
            ],
        ),
    ]
