# Generated by Django 2.0.2 on 2018-02-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20180218_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='additional_incident_data_infor',
        ),
        migrations.AddField(
            model_name='report',
            name='additional_incident_data_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.Country'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.Weapon'),
        ),
    ]
